AWSTemplateFormatVersion: "2010-09-09"
Description: Application stack for Flowboard BE

Resources:
  FlowboardBEAppAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FlowboardBEAppAccessRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: FlowboardBEAppAccessRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:*"
                Resource: "*"

  FlowboardBEAppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FlowboardBEAppInstanceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - tasks.apprunner.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: FlowboardBEAppInstanceRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:*"
                  - "events:*"
                  - "s3:*"
                Resource: "*"

  FlowboardBEAutoScaling:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: FlowboardBEAutoScaling
      MaxSize: 1
      MinSize: 0


  FlowboardBEApp:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: Flowboard-be-app
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier:
            !Join
            - ""
            - - !ImportValue FlowboardBEECRRepositoryUri
              - ":latest"
          ImageRepositoryType: ECR
          ImageConfiguration:
            RuntimeEnvironmentSecrets:

            RuntimeEnvironmentVariables:

            Port: "3000"
        AutoDeploymentsEnabled: true
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt FlowboardBEAppAccessRole.Arn
      InstanceConfiguration:
        Cpu: "0.25 vCPU"
        Memory: "0.5 GB"
        InstanceRoleArn: !GetAtt FlowboardBEAppInstanceRole.Arn
      AutoScalingConfigurationArn: !GetAtt FlowboardBEAutoScaling.AutoScalingConfigurationArn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: "/api/health"

Outputs:
  FlowboardAppServiceArn:
    Description: The ID of the created flowboard BE App
    Value: !GetAtt FlowboardBEApp.ServiceArn