AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for Flowboard github setup

Resources:
  GithubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com

  GithubActionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubActions
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:torann10/flowboard:ref:refs/heads/main
      Policies:
        - PolicyName: GithubActionsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "organizations:*"
                  - "cloudformation:*"
                  - "ecr:*"
                  - "ec2:*"
                  - "ecs:*"
                Resource: "*"